# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='body',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
